const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  minimize: () => ipcRenderer.send('win:minimize'),
  maximize: () => ipcRenderer.send('win:maximize'),
  close: () => ipcRenderer.send('win:close'),
  getStatic: () => ipcRenderer.invoke('sys:static'),
  getSnapshot: () => ipcRenderer.invoke('sys:snapshot'),
  killProcess: (pid) => ipcRenderer.invoke('sys:kill', pid),
  getIcon: (exePath) => ipcRenderer.invoke('sys:icon', exePath),
  describeApps: (paths) => ipcRenderer.invoke('sys:describeBatch', paths),
  listStartup: () => ipcRenderer.invoke('startup:list'),
  toggleStartup: (entry) => ipcRenderer.invoke('startup:toggle', entry),
  getTempInfo: () => ipcRenderer.invoke('optimize:tempInfo'),
  clearTemp: () => ipcRenderer.invoke('optimize:clearTemp'),
  emptyRecycleBin: () => ipcRenderer.invoke('optimize:emptyRecycleBin'),
  flushDns: () => ipcRenderer.invoke('optimize:flushDns'),
  setPriority: (pid, level) => ipcRenderer.invoke('sys:setPriority', pid, level),
  getNetConnections: () => ipcRenderer.invoke('sys:netConnections'),
  openAppsSettings: () => ipcRenderer.invoke('sys:openAppsSettings'),
  listDevices: () => ipcRenderer.invoke('devices:list'),
  toggleDevice: (instanceId, enable) => ipcRenderer.invoke('devices:toggle', instanceId, enable),
  uninstallDevice: (instanceId) => ipcRenderer.invoke('devices:uninstall', instanceId),
  scanDevices: () => ipcRenderer.invoke('devices:scan'),
  openDeviceProperties: (instanceId) => ipcRenderer.invoke('devices:openProperties', instanceId),
  openDeviceManager: () => ipcRenderer.invoke('devices:openManager'),
  enterMiniMode: () => ipcRenderer.send('mini:enter'),
  exitMiniMode: () => ipcRenderer.send('mini:exit'),
});
